### GET request to example server
GET http://localhost:8082/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJza3VtYXI5QGdtYWlsLmNvbSIsInVzZXJJZCI6MTQsImlhdCI6MTc2NzU0MzkyNywiZXhwIjoxNzY3NTc5OTI3fQ.RqZ8hAvfsuQG5n7o4NFmoogSXqFxP0vFfSiLyi8tv3E
###