POST http://localhost:8082/auth/signup
Content-Type: application/json

{
    "username" : "skumar9@gmail.com",
    "password" : "12345",
    "name" : "sunny",
    "roles" : [
        "USER",
        "ADMIN",
        "SUPERADMIN"
    ]
}